name: issue label automation
on:
  issues:
    types:
      - labeled
env:
  PROJECT_NAME: Theme-Research project
jobs:
  issue_labels:
  move_assigned_card:
    runs-on: ubuntu-latest
    name: Move assigned card
    steps:
      - uses: nipe0324/update-project-v2-item-field@v2.0.1
        if: "github.event.label.name == 'Status: Cancelled'"
        with:
          project-url: https://github.com/orgs/Theme-Research-org/projects/3
          github-token: ${{ secrets.GHPROJECT_TOKEN }}
          field-name: Status
          field-value: Cancelled