name: 'Manage Issues for Project'

on: 
  issues:
    types: [labeled]

jobs:
  manage-issues-for-project:
    runs-on: ubuntu-latest
    steps:
      - name: Move issues which have a Available label to the project board column called Todo
        if: github.event.label.name == 'todo'
        uses: kalgurn/update-project-item-status@v0.0.1
        with:
          project-url: https://github.com/orgs/Theme-Research-org/projects/3
          github-token: ${{ secrets.GHPROJECT_TOKEN }}
          item-id: ${{github.event.issue.id}}
          status: Todo

      - name: Move issues which have a In Progress label to the project board column called In Progress
        if: github.event.label.name == '状態：進行中'
        uses: kalgurn/update-project-item-status@v0.0.1
        with:
          project: https://github.com/orgs/Theme-Research-org/projects/3
          github-token: ${{ secrets.GHPROJECT_TOKEN }}
          item-id: ${{github.event.issue.id}}
          status: In Progress

      - name: Move issues which have a Completed label to the project board column called Completed
        if: github.event.label.name == '状態：完了'
        uses: kalgurn/update-project-item-status@v0.0.1
        with:
          project: https://github.com/orgs/Theme-Research-org/projects/3
          github-token: ${{ secrets.GHPROJECT_TOKEN }}
          item-id: ${{github.event.issue.id}}
          status: Completed
        
