name: issue label automation
on:
  issues:
    types:
      - reopened
      - opened
      - closed
      - assigned
env:
  PROJECT_NAME: Theme-Research project
jobs:
  issue_labels:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add Todo label
        if: "github.event.action == 'opened'"
        uses: andymckay/labeler@1.0.2
        with:
          add-labels: "status: Todo"
          remove-labels: "status: In progress, status: Completed"
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}
      - name: Add In progress label
        if: "github.event.action == 'assigned' || github.event.action == 'reopened'"
        uses: andymckay/labeler@1.0.2
        with:
          add-labels: "status: In progress"
          remove-labels: "status: Todo, status: Completed"
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}
      - name: Add Completed label
        if: "github.event.action == 'closed' && github.event.issue.state_reason == 'completed'"
        uses: andymckay/labeler@1.0.2
        with:
          add-labels: "status: Completed"
          remove-labels: "status: In progress, status: Todo"
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}

  move_assigned_card:
    runs-on: ubuntu-latest
    name: Move assigned card
    steps:
      - uses: alex-page/github-project-automation-plus@v0.3.0
        if: "github.event.action == 'assigned'"
        with:
          project: ${{env.PROJECT_NAME}}
          column: In Progress
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}
