name: 'Manage Issues for Project'

on: 
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]

jobs:
  manage-issues-for-project:
    runs-on: ubuntu-latest
    steps:
      - name: Move issues which have a Available label to the project board column called Todo
        if: github.event.label.name == '状態：開始前'
        uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: Theme-Research Project
          column: Todo
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}

      - name: Move issues which have a In Progress label to the project board column called In Progress
        if: github.event.label.name == '状態：進行中'
        uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: Theme-Research Project
          column: In Progress
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}

      - name: Move issues which have a Completed label to the project board column called Completed
        if: github.event.label.name == '状態：完了'
        uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: Theme-Research Project
          column: Completed
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}
